<a href="https://colab.research.google.com/github/anthonybrown0528/csc-442-course-project/blob/main/notebook/hw7/model_comparison_description_score_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
filepath = 'https://raw.githubusercontent.com/anthonybrown0528/csc-442-course-project/refs/heads/main/dataset/clean/hw6/netflix_film_imdb_scores_cleaned_descriptions_df.csv'
df = pd.read_csv(filepath)

In [16]:
df.head()

title  \
0  Monty Python and the Holy Grail   
1                     My Fair Lady   
2                  The Blue Lagoon   
3                 Bonnie and Clyde   
4             The Guns of Navarone   

                                       description_x  release_year  runtime  \
0  King Arthur accompany squire recruit Knights R...          1975       91   
1  snobbish phonetics professor agree wager take ...          1964      170   
2  Two small child ship cook survive shipwreck fi...          1980      104   
3  In 1930s bore waitress Bonnie Parker fall love...          1967      110   
4  team allied saboteur assign impossible mission...          1961      158   

     imdb_id  imdb_score  imdb_votes show_id   type  \
0  tt0071853         8.2      530877   s4218  Movie   
1  tt0058385         7.8       94121   s1127  Movie   
2  tt0080453         5.8       69053    s176  Movie   
3  tt0061418         7.7      111189   s6359  Movie   
4  tt0054953         7.5       50150    s178  Movie   

                     director  ...                        country  \
0  Terry Gilliam, Terry Jones  ...                 United Kingdom   
1                George Cukor  ...                  United States   
2              Randal Kleiser  ...                  United States   
3                 Arthur Penn  ...                  United States   
4             J. Lee Thompson  ...  United Kingdom, United States   

          date_added age_certification num_releases  \
0    January 2, 2019                PG            1   
1      April 1, 2021                 G            1   
2  September 1, 2021                 R            1   
3    January 1, 2021                 R            1   
4  September 1, 2021             TV-14            1   

                                      listed_in  \
0  Action & Adventure, Classic Movies, Comedies   
1              Classic Movies, Music & Musicals   
2                       Dramas, Romantic Movies   
3    Action & Adventure, Classic Movies, Dramas   
4            Action & Adventure, Classic Movies   

                                       description_y num_listed_in  \
0  The Monty Python comedy clan skewers King Arth...             3   
1  When a Cockney flower girl takes elocution les...             2   
2  Two shipwrecked children, stranded for years o...             2   
3  Bonnie Parker and Clyde Barrow are young, in l...             3   
4  During World War II, British forces launch an ...             2   

       first_cast cast_freq_mean  genre_freq_mean  
0  Graham Chapman      10.888889       831.000000  
1  Audrey Hepburn       1.083333       203.500000  
2  Brooke Shields       1.375000      1446.500000  
3   Warren Beatty       1.777778      1076.333333  
4    Gregory Peck       1.300000       459.500000  

[5 rows x 21 columns]

In [17]:
column_subset = ['title', 'release_year', 'listed_in', 'description_x', 'imdb_score']
query_df = df[column_subset]

query_df

title  release_year  \
0        Monty Python and the Holy Grail          1975   
1                           My Fair Lady          1964   
2                        The Blue Lagoon          1980   
3                       Bonnie and Clyde          1967   
4                   The Guns of Navarone          1961   
...                                  ...           ...   
2472           Myriam Fares: The Journey          2021   
2473          The Tambour of Retribution          2021   
2474                       Pitta Kathalu          2021   
2475             Loyiso Gola: Unlearning          2021   
2476  Mighty Little Bheem: Kite Festival          2021   

                                              listed_in  \
0          Action & Adventure, Classic Movies, Comedies   
1                      Classic Movies, Music & Musicals   
2                               Dramas, Romantic Movies   
3            Action & Adventure, Classic Movies, Dramas   
4                    Action & Adventure, Classic Movies   
...                                                 ...   
2472  Documentaries, International Movies, Music & M...   
2473      Dramas, International Movies, Romantic Movies   
2474                  International TV Shows, TV Dramas   
2475                                    Stand-Up Comedy   
2476                              Kids' TV, TV Comedies   

                                          description_x  imdb_score  
0     King Arthur accompany squire recruit Knights R...         8.2  
1     snobbish phonetics professor agree wager take ...         7.8  
2     Two small child ship cook survive shipwreck fi...         5.8  
3     In 1930s bore waitress Bonnie Parker fall love...         7.7  
4     team allied saboteur assign impossible mission...         7.5  
...                                                 ...         ...  
2472  From pregnancy album preparation Lebanese sing...         2.3  
2473  son swordsman fall love daughter Tagaga social...         6.9  
2474  Four different woman four journey love betraya...         5.1  
2475  South African comedian Loyiso Gola serve filte...         5.9  
2476  With winter behind Bheem townspeople usher sun...         8.8  

[2477 rows x 5 columns]

In [18]:
features = ['title', 'release_year', 'genre', 'description']

In [19]:
def separate_genre_df(data):
  movie_genre_map = {
      'title': [],
      'release_year': [],
      'genre': [],
      'description': [],
      'imdb_score': []
  }

  for _, row in data.iterrows():
    genres = row['listed_in'].split(',')

    for genre in genres:
      movie_genre_map['title'].append(row['title'])
      movie_genre_map['release_year'].append(row['release_year'])
      movie_genre_map['genre'].append(genre.strip())
      movie_genre_map['description'].append(row['description_x'].strip())
      movie_genre_map['imdb_score'].append(row['imdb_score'])


  movie_genre_df = pd.DataFrame(movie_genre_map)

  movie_genre_df = movie_genre_df[movie_genre_df['genre'] != 'International Movies']
  movie_genre_df = movie_genre_df[movie_genre_df['genre'] != 'International TV Shows']

  movie_genre_df

  return movie_genre_df

data_cleaned_df = separate_genre_df(query_df)

feature_df = data_cleaned_df[features]
target_df = data_cleaned_df['imdb_score']

data_cleaned_df['genre'].nunique()

39

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(feature_df, target_df, test_size=0.3, random_state=42)

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [23]:
n_splits = 5

cv = KFold(n_splits=n_splits)
cv_scores = np.zeros(n_splits)
errors = np.zeros(n_splits)

for index, (train, val) in enumerate(cv.split(X_train, y_train)):
  X_train_train = X_train.iloc[train]
  y_train_train = y_train.iloc[train]

  X_train_val = X_train.iloc[val]
  y_train_val = y_train.iloc[val]

  # Set up a pipeline for feature extraction
  genre_probabilities_pipeline = Pipeline([('vectorizer', CountVectorizer(stop_words='english')), ('topic_model', MultinomialNB())])
  genre_probabilities_pipeline = genre_probabilities_pipeline.fit(X=X_train_train['description'], y=X_train_train['genre'])

  # Set up a pipeline for regression
  X_train_tmp = X_train_train.copy()

  X_train_tmp['imdb_score'] = y_train_train
  X_train_tmp = X_train_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_train = X_train_tmp[features]
  y_train_train = X_train_tmp['imdb_score']

  compressed_feature = genre_probabilities_pipeline.predict_proba(X=X_train_train['description'])

  genre_weights_score_pipeline = Pipeline([('regressor', LinearRegression())])

  genre_weights_score_pipeline = genre_weights_score_pipeline.fit(X=compressed_feature, y=y_train_train)

  # Validate the final model

  X_val_tmp = X_train_val.copy()

  X_val_tmp['imdb_score'] = y_train_val
  X_val_tmp = X_val_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_val = X_val_tmp[features]
  y_train_val = X_val_tmp['imdb_score']

  compressed_feature = genre_probabilities_pipeline.predict_proba(X=X_train_val['description'])
  score = genre_weights_score_pipeline.score(X=compressed_feature, y=y_train_val)

  cv_scores[index] = score
  errors[index] = mean_squared_error(y_train_val, genre_weights_score_pipeline.predict(compressed_feature))

In [24]:
print(cv_scores)
cv_scores.mean()

[0.0938909  0.09746741 0.10848268 0.05511257 0.07077847]


np.float64(0.08514640591255193)

In [25]:
print(errors)
errors.mean()

[1.13977267 1.2235283  1.26606114 1.11798943 1.20711184]


np.float64(1.1908926749149626)

In [26]:
n_splits = 5

cv = KFold(n_splits=n_splits)
cv_scores = np.zeros(n_splits)

for index, (train, val) in enumerate(cv.split(X_train, y_train)):
  X_train_train = X_train.iloc[train]
  y_train_train = y_train.iloc[train]

  X_train_val = X_train.iloc[val]
  y_train_val = y_train.iloc[val]

  # Set up a pipeline for feature extraction
  genre_probabilities_pipeline = Pipeline([('vectorizer', TfidfVectorizer(stop_words='english')), ('topic_model', MultinomialNB())])
  genre_probabilities_pipeline = genre_probabilities_pipeline.fit(X=X_train_train['description'], y=X_train_train['genre'])

  # Set up a pipeline for regression
  X_train_tmp = X_train_train.copy()

  X_train_tmp['imdb_score'] = y_train_train
  X_train_tmp = X_train_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_train = X_train_tmp[features]
  y_train_train = X_train_tmp['imdb_score']

  compressed_feature = genre_probabilities_pipeline.predict_proba(X=X_train_train['description'])

  genre_weights_score_pipeline = Pipeline([('regressor', LinearRegression())])

  genre_weights_score_pipeline = genre_weights_score_pipeline.fit(X=compressed_feature, y=y_train_train)

  # Validate the final model

  X_val_tmp = X_train_val.copy()

  X_val_tmp['imdb_score'] = y_train_val
  X_val_tmp = X_val_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_val = X_val_tmp[features]
  y_train_val = X_val_tmp['imdb_score']

  compressed_feature = genre_probabilities_pipeline.predict_proba(X=X_train_val['description'])
  score = genre_weights_score_pipeline.score(X=compressed_feature, y=y_train_val)

  cv_scores[index] = score
  errors[index] = mean_squared_error(y_train_val, genre_weights_score_pipeline.predict(compressed_feature))

In [27]:
print(cv_scores)
cv_scores.mean()

[0.12189837 0.09665193 0.1310359  0.0473204  0.08724317]


np.float64(0.09682995369621865)

In [28]:
print(errors)
errors.mean()

[1.10454276 1.22463382 1.23403286 1.12720911 1.18572325]


np.float64(1.1752283607190426)

In [29]:
from sklearn.decomposition import LatentDirichletAllocation

In [30]:
n_splits = 5

cv = KFold(n_splits=n_splits)
cv_scores = np.zeros(n_splits)

for index, (train, val) in enumerate(cv.split(X_train, y_train)):
  X_train_train = X_train.iloc[train]
  y_train_train = y_train.iloc[train]

  X_train_val = X_train.iloc[val]
  y_train_val = y_train.iloc[val]

  # Set up a pipeline for regression
  X_train_tmp = X_train_train.copy()

  X_train_tmp['imdb_score'] = y_train_train
  X_train_tmp = X_train_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_train = X_train_tmp[features]
  y_train_train = X_train_tmp['imdb_score']

  genre_weights_score_pipeline = Pipeline([
      ('vectorizer', TfidfVectorizer(stop_words='english')),
      ('topic_model', LatentDirichletAllocation(n_components=50, random_state=42)),
      ('regressor', LinearRegression())]
  )

  genre_weights_score_pipeline = genre_weights_score_pipeline.fit(X=X_train_train['description'], y=y_train_train)

  # Validate the final model

  X_val_tmp = X_train_val.copy()

  X_val_tmp['imdb_score'] = y_train_val
  X_val_tmp = X_val_tmp.drop_duplicates(subset=['title', 'release_year'])

  X_train_val = X_val_tmp[features]
  y_train_val = X_val_tmp['imdb_score']

  score = genre_weights_score_pipeline.score(X=X_train_val['description'], y=y_train_val)

  cv_scores[index] = score
  errors[index] = mean_squared_error(y_train_val, genre_weights_score_pipeline.predict(X_train_val['description']))

cv_scores

array([0.01048254, 0.01571268, 0.03525614, 0.01438399, 0.00972956])

In [31]:
print(cv_scores)
cv_scores.mean()

[0.01048254 0.01571268 0.03525614 0.01438399 0.00972956]


np.float64(0.017112982278118704)

In [32]:
print(errors)
errors.mean()

[1.24469002 1.33436001 1.37005157 1.16617943 1.28641786]


np.float64(1.280339777263522)